### ISSUE TITLE
pano_ros broken because of missing opencv_test dependency

### ISSUE THREAD

**Issue by bit-pirate** [turtlebot/turtlebot_apps#23]
When trying to run the pano app, pano_ros' capture_server is crashing.
Looks like there is a missing dependency in open_cv. When pulling in stuff from open_cv, opencv_test can't be found. 

```
$ rosrun pano_ros capture_server.py 
Traceback (most recent call last):
  File "/opt/kobuki_workspace/turtlebot_apps/software/pano/pano_ros/nodes/capture_server.py", line 63, in <module>
    from cv_bridge import CvBridge, CvBridgeError
  File "/opt/ros/groovy/lib/python2.7/dist-packages/cv_bridge/__init__.py", line 1, in <module>
    from cv_bridge import *
  File "/opt/ros/groovy/lib/python2.7/dist-packages/cv_bridge/cv_bridge.py", line 2, in <module>
    roslib.load_manifest('opencv_tests')
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslib/launcher.py", line 62, in load_manifest
    sys.path = _generate_python_path(package_name, _rospack) + sys.path
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslib/launcher.py", line 93, in _generate_python_path
    m = rospack.get_manifest(pkg)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 133, in get_manifest
    return self._load_manifest(name)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 172, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 164, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
```

Is that a bug in ROS' cv_bridge?

**Comment by bit-pirate** [comment]
Filled a bug at the vision_opencv stack:
https://github.com/ros-perception/vision_opencv/issues/1
