### ISSUE TITLE
Problem on Turtlebot_panorama when installed from deb packages

### ISSUE THREAD

**Issue by corot** [turtlebot/turtlebot_apps#38]
No idea what is cv_bridge_boost, but looks like it's missing on the robot running just deb packages (yujin-kobuki1-laptop)

[ERROR] [WallTime: 1359369129.412966] bad callback: <bound method Subscriber.callback of <message_filters.Subscriber instance at 0x1c0a6c8>>
Traceback (most recent call last):
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rospy/topics.py", line 683, in _invoke_callback
    cb(msg)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/message_filters/__init__.py", line 72, in callback
    self.signalMessage(msg)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/message_filters/**init**.py", line 55, in signalMessage
    cb(_(msg + args))
  File "/opt/ros/groovy/lib/python2.7/dist-packages/message_filters/**init**.py", line 141, in add
    self.signalMessage(_msgs)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/message_filters/**init**.py", line 55, in signalMessage
    cb(*(msg + args))
  File "/opt/ros/groovy/stacks/turtlebot_apps/software/pano/pano_ros/nodes/capture_server.py", line 220, in capture_fn
    self._capture_job.capture_fn(image, info)
  File "/opt/ros/groovy/stacks/turtlebot_apps/software/pano/pano_ros/nodes/capture_server.py", line 298, in __call__
    cv_image = self.bridge.imgmsg_to_cv(image, "rgb8")
  File "/opt/ros/groovy/lib/python2.7/dist-packages/cv_bridge/core.py", line 101, in imgmsg_to_cv
    source_type = self.encoding_as_cvtype(img_msg.encoding)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/cv_bridge/core.py", line 73, in encoding_as_cvtype
    from cv_bridge.boost.cv_bridge_boost import getCvType
ImportError: No module named cv_bridge_boost

**Comment by stonier** [comment]
Hmm, cv_bridge is installed so I'm wondering if cv_bridge missed a trick building it's deb.

**Comment by corot** [comment]
Well, this issue vanished by itself. I have tried to reproduce in two different ros installations and doesn't happen anymore.
